#!/usr/bin/env python3
"""Mechanical half of the AGENTS.md "Comments" ceiling, ported from Munin's scripts/comment-budget.py.

Fails when a diff adds more than BUDGET lines of comment text to one block in src/; test/ only warns.
XML docs on the package's public surface are exempt, because their reader has only the package.

Line-based: a line inside a multi-line string literal that starts with // or /* reads as a comment.
"""
import argparse
import itertools
import os
import re
import subprocess
import sys
from collections import namedtuple

BUDGET = 3
Syntax = namedtuple("Syntax", "line blocks quotes")
CSHARP = Syntax("//", (("/*", "*/"),), "\"'")
JAVASCRIPT = Syntax("//", (("/*", "*/"),), "\"'`")
# Apostrophes are prose in markup, so only double quotes delimit a string there.
RAZOR = Syntax("//", (("@*", "*@"), ("<!--", "-->"), ("/*", "*/")), '"')
SYNTAXES = {".cs": CSHARP, ".razor": RAZOR, ".js": JAVASCRIPT, ".mjs": JAVASCRIPT}

ERROR_SCOPE = re.compile(r"^src/")
WARN_SCOPE = re.compile(r"^test/")
PACKAGE = re.compile(r"^src/Fhi\.Munin\.Explorer/")
SKIP = re.compile(r"(/(bin|obj)/|\.g\.cs$|\.Designer\.cs$)")
GENERATED = re.compile(r"<auto-generated|AUTO-GENERATED|DO NOT EDIT|DO NOT HAND-EDIT")
ALLOWLIST = ".github/comment-budget-allowlist.txt"
TAG_ONLY = re.compile(r"^(</?[A-Za-z][^>]*>\s*)*$")
# One line per parameter is the shape of a documented member, not padding.
PER_MEMBER = re.compile(r"^(<(param|typeparam|returns|exception)\b.*</\2>|@(param|returns|throws)\b.*)$")

MODIFIERS = r"(?:public|internal|private|protected|static|sealed|abstract|partial|readonly|ref|unsafe|file|new)"
TYPE_DECL = re.compile(rf"^((?:{MODIFIERS}\s+)*)(class|record|struct|interface|enum)\s")
MEMBER_MODIFIERS = {"public", "internal", "private", "protected", "static", "sealed", "abstract", "partial",
                    "readonly", "ref", "unsafe", "file", "new", "virtual", "override", "async", "extern",
                    "const", "event", "required", "volatile"}
ATTRIBUTES = re.compile(r"^(\[[^\]]*\]\s*)+")
PUNCTUATION_ONLY = re.compile(r"^[{}()\[\];,]*$")


def git(*args):
    return subprocess.run(
        ["git", "-c", "core.quotepath=false", *args],
        capture_output=True, text=True, encoding="utf-8", errors="replace", check=True,
    ).stdout


def opens_block(s, syntax):
    """The closing token when a code line ends inside an unterminated block comment, else None."""
    quote, i = None, 0
    while i < len(s):
        c = s[i]
        if quote:
            if c == "\\":
                i += 1
            elif c == quote:
                quote = None
        elif c in syntax.quotes:
            quote = c
        elif s.startswith(syntax.line, i):
            return None
        else:
            for opener, closer in syntax.blocks:
                if s.startswith(opener, i):
                    end = s.find(closer, i + len(opener))
                    if end < 0:
                        return closer
                    i = end + len(closer) - 1
                    break
        i += 1
    return None


def classify(lines, syntax=CSHARP):
    """One kind per line: code, blank, text (comment with words) or tag (marker or XML tag only)."""
    kinds, closer = [], None
    for raw in lines:
        s = raw.strip()
        if closer is None and s.startswith(syntax.line):
            text = s.lstrip("/").strip()
        else:
            opener = None if closer else next((p for p in syntax.blocks if s.startswith(p[0])), None)
            if closer is None and opener is None:
                closer = opens_block(s, syntax)
                kinds.append("code" if s else "blank")
                continue
            body = s[len(opener[0]):] if opener else s
            closer = opener[1] if opener else closer
            if closer in body:
                text, rest = body.split(closer, 1)
                rest = rest.strip()
                closer = None
                if rest and not rest.startswith(syntax.line):
                    closer = opens_block(rest, syntax)
                    kinds.append("code")
                    continue
            else:
                text = body
            text = text.lstrip("*").strip()
        kinds.append("tag" if TAG_ONLY.match(text) or PER_MEMBER.match(text) else "text")
    return kinds


def blocks(kinds):
    out, start = [], None
    for i, kind in enumerate([*kinds, "code"]):
        if kind in ("text", "tag"):
            start = i if start is None else start
        elif start is not None:
            out.append((start, i))
            start = None
    return out


def indent(line):
    return len(line) - len(line.lstrip())


def is_public(modifiers):
    words = modifiers.split()
    return "public" in words or ("protected" in words and "private" not in words)


def enclosing_types(lines, start, razor):
    """(kind, public) for each type around line `start`, innermost first; None when not decidable."""
    types, level = [], indent(lines[start])
    for i in range(start - 1, -1, -1):
        s = lines[i].strip()
        if not s or indent(lines[i]) >= level or PUNCTUATION_ONLY.match(s):
            continue
        level = indent(lines[i])
        if razor and re.match(r"^@(code|functions)\b", s):
            # A component's generated class is public; Blazor offers no way to declare it otherwise.
            return [*types, ("class", True)]
        m = TYPE_DECL.match(ATTRIBUTES.sub("", s))
        if m:
            types.append((m.group(2), is_public(m.group(1))))
        elif level == 0:
            break
    return None if razor else types


def is_public_doc(path, lines, start, end):
    """True for a /// block documenting a type or member a host can see in the published package."""
    if not PACKAGE.search(path) or not all(l.strip().startswith("///") for l in lines[start:end]):
        return False
    decl = next((ATTRIBUTES.sub("", l.strip()) for l in lines[end:] if ATTRIBUTES.sub("", l.strip())), "")
    types = enclosing_types(lines, start, path.endswith(".razor"))
    if types is None or not all(public for _, public in types):
        return False
    modifiers = " ".join(itertools.takewhile(lambda w: w in MEMBER_MODIFIERS, decl.split()))
    if is_public(modifiers):
        return True
    access = {"public", "internal", "private", "protected", "file"}
    # Interface and enum members carry no modifier and are as visible as the type.
    return not access & set(modifiers.split()) and bool(types) and types[0][0] in ("interface", "enum")


def added_lines(base):
    return parse_added(git("diff", "--merge-base", base, "-U0", "-M", "--no-color", "--", *(f"*{e}" for e in SYNTAXES)))


def parse_added(diff):
    added, path = {}, None
    for line in diff.splitlines():
        if line.startswith("+++ "):
            # Git appends a tab to a header path that contains a space.
            path = None if line == "+++ /dev/null" else line[6:].split("\t", 1)[0]
            if path:
                added.setdefault(path, set())
        elif line.startswith("@@") and path:
            m = re.search(r"\+(\d+)(?:,(\d+))?", line)
            start, count = int(m.group(1)), int(m.group(2) or 1)
            added[path].update(range(start, start + count))
    return added


def load_allowlist():
    entries = []
    if os.path.exists(ALLOWLIST):
        for line in read_lines(ALLOWLIST):
            if line.strip() and not line.lstrip().startswith("#"):
                parts = [p.strip() for p in line.split("|")]
                if len(parts) != 3 or not all(parts):
                    sys.exit(f"{ALLOWLIST}: expected '<path> | <text in block> | <reason>', got: {line.strip()}")
                entries.append(parts)
    return entries


def read_lines(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        return f.read().splitlines()


def check(base):
    allow = load_allowlist()
    errors, warnings = [], []
    for path, added in sorted(added_lines(base).items()):
        in_scope = ERROR_SCOPE.search(path) or WARN_SCOPE.search(path)
        if not added or not in_scope or SKIP.search(path) or not os.path.exists(path):
            continue
        lines = read_lines(path)
        if any(GENERATED.search(l) for l in lines[:15]):
            continue
        kinds = classify(lines, SYNTAXES[os.path.splitext(path)[1]])
        warn_only = bool(WARN_SCOPE.search(path))
        for start, end in blocks(kinds):
            text = [i for i in range(start, end) if kinds[i] == "text"]
            new = sum(1 for i in text if i + 1 in added)
            touched = any(i + 1 in added for i in range(start, end))
            block = "\n".join(lines[start:end])
            if not touched or any(p == path and anchor in block for p, anchor, _ in allow):
                continue
            if len(text) > BUDGET and is_public_doc(path, lines, start, end):
                continue
            where = f"file={path},line={start + 1},endLine={end}"
            if new > BUDGET:
                msg = (f"Comment block adds {new} lines of text; the budget is {BUDGET}. Keep the why, "
                       f"move history to the bead. An earned exception goes in {ALLOWLIST}.")
                (warnings if warn_only else errors).append(f"::{'warning' if warn_only else 'error'} {where}::{msg}")
            elif len(text) > BUDGET:
                warnings.append(f"::warning {where}::This change touches a {len(text)}-line comment block; trim it if the change is about that code.")
    for line in errors + warnings:
        print(line)
    print(f"comment-budget: {len(errors)} error(s), {len(warnings)} warning(s)")
    return 1 if errors else 0


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--base", default="origin/main", help="ref to diff against (merge-base is used)")
    sys.exit(check(parser.parse_args().base))


if __name__ == "__main__":
    main()
